global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'time-recorder'
    static_configs:
      - targets: ['time-recorder:3000']

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']  # <-- сюда адрес твоего Jenkins
